name: $(BuildDefinitionName)-$(SourceBranchName)-$(BuildID)

resources:
  repositories:
  - repository: ci-settings
    type: github
    name: angr/ci-settings
    ref: refs/heads/docker_sock
    endpoint: angr

stages:
- template: resources/master.yml@ci-settings
  parameters:
    docker_socket: True
